"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](peach)\
$os\
[](bg:yellow fg:peach)\
$directory\
[](fg:yellow bg:sky)\
$git_branch\
$git_status\
[](fg:sky bg:lavender)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:lavender)\
$line_break$character"""

palette = 'catppuccin_macchiato'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subcrust1 = "#b8c0e0"
subcrust0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[os]
disabled = false
style = "bg:peach fg:base"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:peach fg:base"
style_root = "bg:peach fg:base"
format = '[ $user ]($style)'

[directory]
style = "fg:base bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:sky"
format = '[[ $symbol $branch ](fg:base bg:sky)]($style)'

[git_status]
style = "bg:sky"
format = '[[($all_status$ahead_behind )](fg:base bg:sky)]($style)'

[nodejs]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol( $version) ](fg:base bg:lavender)]($style)'

[c]
symbol = " "
style = "bg:lavender"
format = '[[ $symbol( $version) ](fg:base bg:lavender)]($style)'

[rust]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol( $version) ](fg:base bg:lavender)]($style)'

[golang]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol( $version) ](fg:base bg:lavender)]($style)'

[php]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol( $version) ](fg:base bg:lavender)]($style)'

[java]
symbol = " "
style = "bg:lavender"
format = '[[ $symbol( $version) ](fg:base bg:lavender)]($style)'

[kotlin]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol( $version) ](fg:base bg:lavender)]($style)'

[haskell]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol( $version) ](fg:base bg:lavender)]($style)'

[python]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol( $version) ](fg:base bg:lavender)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $concrust) ](fg:#83a598 bg:mantle)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:mauve)'
vimcmd_replace_symbol = '[](bold fg:mauve)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
